name-template: "Version $RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
filter-by-commitish: true
change-template: "- #$NUMBER $TITLE by @$AUTHOR"

replacers:
  - search: " by @mergify"
    replace: ""

categories:
  - title: ":rocket: Features"
    labels:
      - 'enhancement'
  - title: ":bug: Bug Fixes"
    labels:
      - "bug"
  - title: ":toolbox: Maintenance"
    labels:
      - 'maintenance'
  - title: ':arrow_up: Dependencies'
    labels:
      - 'updates'
  - title: ":open_book: Documentation"
    labels:
      - "documentation"

template: |
  ## Changes

  $CHANGES

footer: |
  ## :bow: Thanks to our contributors
  
  Special thanks to all code contributors who helped with this particular release (they are listed below)!
